### ISSUE TITLE
Toy factory: Rubber ducky disappears too early

### ISSUE THREAD

**Issue by Wuzzy2** [OpenTTD/OpenGFX#49]
If the toy factory does its animation think, you see little rubber duckies going across the conveyor belt. However, the animation is not fully "smooth" at the end. The rubber ducky does not smoothly finish its travel over the conveyor belt. Shortly before it reaches the left building, the rubber ducky disappears. What I expect to happen is for the rubber ducky move all the way to the building until it is no longer visible.

Note, this issue is only for the END of the animation. The rest of the rubber ducky movement is fine.

Version: 0.6.0

**Comment by Andrew350** [comment]
It seems the buildings are offset too far to the left, causing the animated sprites to run outside the bounding box and not render properly. Adding +10 to x-offset and -6 to y-offset to all building sprites would fix it.

**Comment by frosch123** [comment]
The animations of the original industries cannot be changed. They are the same as in 1995 by definition.

**Comment by Wuzzy2** [comment]
I don't understand …
The point of OpenGFX is literally to change the official aniation of the toy factory. And now you're saying it cannot be changed ever? That doesn't make sense.

I don't think you understand what I was trying to say. Please look at the toy factory anymation in-game and see if there is anything wrong with the rubber ducky. It poofs out of existance at the end of the conveyor belt.

How is it that it cannot be fixed?

Is the animation of the original toy factory in the original graphics broken as well?

**Comment by LordAro** [comment]
I'm not saying that this isn't an issue, but "The point of OpenGFX is literally to change the official aniation of the toy factory" is not correct

OpenGFX (and all the other sets) do graphics only. They make no changes regarding offsets or anything else - they cannot, it's part of what makes it a baseset rather than a NewGRF. In general, if the issue is in more than one baseset, then it's a "fundamental" issue that cannot be changed. If it's just OGFX, then it's probably an issue in the graphics that can be fixed.

Since it's not clear what exactly you're referring to, perhaps a short gif of what you're seeing?

**Comment by Wuzzy2** [comment]
With "change" I mean "it looks differently than the original". Nothing more. I don't mean "technical change" neccessarily. I wan't the one who brought up this offset stuff. I don't know how OpenGFX works, obviously.

> Since it's not clear what exactly you're referring to, perhaps a short gif of what you're seeing?

No GIF, but a screenshot:
https://satoshiupload.com/images/awQpULrCgE.png

Before/after comparison. Right is a very few milliseconds after the left image. The ducky should have moved a few pixels to the left, but as you see, the ducky disappeared, rather than smoothly moving "behind" the house.

**Comment by nielsmh** [comment]
The animation is not defined or controlled by OpenGFX, it's built into the game itself. That makes it a (possible) bug in the game, not with OpenGFX.

Also please attach images to the message in GitHub instead of using external hosting.
![image](https://user-images.githubusercontent.com/1062071/107095493-35b54a80-6809-11eb-8d96-f92303806dd8.png)

**Comment by frosch123** [comment]
It's the same with original graphics:
![toyfactory](https://user-images.githubusercontent.com/23150643/107096813-d1e05100-680b-11eb-9b9c-c246867a8791.png)

However, I checked the sprites: the building on the left extends onto the tile in the middle, so it is possible to draw it wider.

**Comment by Wuzzy2** [comment]
Ah, OK. Then it makes sense.
